# Generated by Django 4.2.1 on 2024-05-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_test',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
